### ISSUE TITLE
BigQuery: insertAll(builder.build()) throws java.lang.IllegalArgumentException without description

### ISSUE THREAD

**Issue by JuanArosemenaAL** [googleapis/java-bigquery#1321]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: Windows 10 64-bit
3. Java version: openjdk-15.0.2
4. bigquery version(s): 1.128

#### Steps to reproduce

  1. Run a streaming insert for a large chunk of data into a table.
  2. Sometimes, not always, for certain tables the insertAll() method of BigQuery throws an IllegalArgumentException, but no clear cause is displayed.

#### Code example

```java
           BigQuery bigquery = BigQueryOptions.getDefaultInstance().getService();

            // Get table
            TableId tableId = TableId.of(datasetName, tableName);

            // Inserts rowContent into datasetName:tableId.
            int i = 0;
            InsertAllRequest.Builder builder = InsertAllRequest.newBuilder(tableId);
            builder.setIgnoreUnknownValues(true).setSkipInvalidRows(true);
            for (Map<String, Object> rowContent : bqStore.log_group_values.get(tableName)) {
                builder = builder.addRow(rowContent);

                i++;
                // Every 30000 rows or when total rows are reached make an insert because of BigQuery limits
                if (i % 30000 == 0 || i >= bqStore.log_group_values.get(tableName).size()) {
                    InsertAllResponse response =
                            bigquery.insertAll(builder.build());

                    if (response.hasErrors()) {
                        // If any of the insertions failed, this lets you inspect the errors
                        for (Map.Entry<Long, List<BigQueryError>> entry : response.getInsertErrors().entrySet()) {
                            System.out.println("Response error: \n" + entry.getValue());
                            return false;
                        }
                    }
                    builder = InsertAllRequest.newBuilder(tableId);
                }

            }
```

#### Stack trace
```
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:35)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:128)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:173)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:173)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:146)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:173)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:105)
	at com.google.api.client.http.json.JsonHttpContent.writeTo(JsonHttpContent.java:73)
	at com.google.api.client.http.GZipEncoding.encode(GZipEncoding.java:50)
	at com.google.api.client.http.HttpEncodingStreamingContent.writeTo(HttpEncodingStreamingContent.java:48)
	at com.google.api.client.http.javanet.NetHttpRequest$DefaultOutputWriter.write(NetHttpRequest.java:76)
	at com.google.api.client.http.javanet.NetHttpRequest.writeContentToOutputStream(NetHttpRequest.java:171)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:117)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:492)
	at com.google.cloud.bigquery.BigQueryImpl.insertAll(BigQueryImpl.java:1036)
	at com.aerialoop.Main.insertAllBigQuery(Main.java:935)
	at com.aerialoop.Main.process(Main.java:344)
	at com.aerialoop.Main.main(Main.java:1065)
```

#### Any additional information below
I'm not sure what conditions on the inserting data could cause this error.

Thanks!

**Comment by JuanArosemenaAL** [comment]
Sorry, forgot to add I'm using Java 11.

**Comment by stephaniewang526** [comment]
You could try adding logging statements to help understand your issue. Also, please consider using the [bigquerystorage client write api](https://cloud.google.com/bigquery/docs/write-api) for streaming insert of large amount of data.
