### ISSUE TITLE
No enum constant com.google.cloud.bigquery.Field.Mode

### ISSUE THREAD

**Issue by asaitov** [googleapis/java-bigquery#1655]
#### Environment details

1. API: BigQuery
2. OS type and version: Ubuntu 21.04
3. Java version: 11
4. bigquery version(s): 2.1.6

#### Steps to reproduce

  1. Run the code example.
  2. This code should be returning `Mode.NULLABLE` rather than throwing an exception.

#### Code example

```java
Field.of("test", LegacySQLTypeName.STRING).toBuilder().setMode(null).build().getMode();
```

#### Stack trace
```
java.lang.IllegalArgumentException: No enum constant com.google.cloud.bigquery.Field.Mode.
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.google.cloud.bigquery.Field$Mode.valueOf(Field.java:71)
	at com.google.cloud.bigquery.Field.getMode(Field.java:283)
```

**Comment by asaitov** [comment]
Thank you. Javadoc for `Field.Builder#setMode` method reads
```
Sets the mode of the field. When not specified {@link Mode#NULLABLE} is used.
```
and `null` value is explicitly allowed to be passed as a parameter, see the method body:
```
this.mode = mode != null ? mode.name() : Data.<String>nullOf(String.class);
```
That's why I think the example code above shouldn't fail. Anyway, if it works as intended I'm OK.
