### ISSUE TITLE
BigQuery: listJobs is throwing IAE

### ISSUE THREAD

**Issue by shevek** [googleapis/java-bigquery#17]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
2. OS type and version: Ubuntu 19.04
3. Java version: openjdk version "1.8.0_222"
4. google-cloud-java version(s): com.google.cloud:google-cloud-bigquery:1.96.0

#### Steps to reproduce

Happens about 100 times while listing 65,000 jobs on a project.

#### Code example

```java
bq.listJobs(...);
for (Job job : page.getValues()) { // Throws.
}
```

#### Stack trace
```
java.lang.IllegalArgumentException: Provided dataset is null or empty
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at com.google.cloud.bigquery.TableId.<init>(TableId.java:67)
        at com.google.cloud.bigquery.TableId.fromPb(TableId.java:109)
        at com.google.cloud.bigquery.QueryJobConfiguration$Builder.<init>(QueryJobConfiguration.java:178)
        at com.google.cloud.bigquery.QueryJobConfiguration$Builder.<init>(QueryJobConfiguration.java:89)
        at com.google.cloud.bigquery.QueryJobConfiguration.fromPb(QueryJobConfiguration.java:903)
        at com.google.cloud.bigquery.JobConfiguration.fromPb(JobConfiguration.java:128)
        at com.google.cloud.bigquery.JobInfo$BuilderImpl.<init>(JobInfo.java:158)
        at com.google.cloud.bigquery.Job.fromPb(Job.java:485)
        at com.google.cloud.bigquery.BigQueryImpl$32.apply(BigQueryImpl.java:1127)
        at com.google.cloud.bigquery.BigQueryImpl$32.apply(BigQueryImpl.java:1124)
        at com.google.common.collect.Iterators$6.transform(Iterators.java:786)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)

```

#### External references such as API reference guides used	

- ?	

#### Any additional information below	

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by pmakani** [comment]
Closing this issue. Feel free to reopen if above reply did not help.

**Comment by shevek** [comment]
Situation still arises, and the above has not helped, because when I call this function, it still throws an exception in code I do not control, but I do not appear to have permission reopen the issue.
