### ISSUE TITLE
BigQuery.writer() removes thread interrupt flag

### ISSUE THREAD

**Issue by mduczek** [googleapis/java-bigquery#1807]
#### Environment details

1. OS type and version: Mac OS 10.15.7
2. Java version: 17
3.  version: com.google.cloud:google-cloud-bigquery = 2.6.2

#### Code example

```java
        Future<?> future = executorService.submit(() -> {
            TableId tableId = TableId.of("dataset1", "table1");
            WriteChannelConfiguration writeChannelConfiguration = WriteChannelConfiguration.newBuilder(tableId)
                    .setWriteDisposition(JobInfo.WriteDisposition.WRITE_TRUNCATE)
                    .setFormatOptions(FormatOptions.parquet())
                    .build();
            JobId jobId = JobId.of("test-job-" + UUID.randomUUID());
            Thread.currentThread().interrupt();
            Preconditions.checkState(Thread.currentThread().isInterrupted(), "Thread should be interrupted");
            Preconditions.checkState(Thread.currentThread().isInterrupted(), "Still interrupted");
            TableDataWriteChannel writer = bigQuery.writer(jobId, writeChannelConfiguration);
            Preconditions.checkState(!Thread.currentThread().isInterrupted(), "bigQuery removes interrupt");
        });
        future.get();
```

#### Any additional information below
We use google-cloud-bigquery java client in our product.
in our product the user can trigger and cancel jobs. We use the standard java executorService which cancels the tasks by setting Thread.interrupt flag.

However, BigQuery client clears thread interrupt flag on `bigQuery.writer(...)`. The correct behavior would be for `bigQuery.writer(...)` to throw if Thread.currentThread().isInterrupted is `true`.

**Comment by prash-mi** [comment]
I tried to reproduce this using the test code you shared and got `java.lang.InterruptedException` while calling `bigQuery.writer(...)` after interrupting the thread, which is expected, let me paste the console log and the test code for your reference: 

Code:
```

private static BigQuery bigQuery = BigQueryOptions.getDefaultInstance().getService();
    static  ExecutorService executorService = Executors.newFixedThreadPool(2);
    public static void main(String[] args) throws Exception {
        Future<?> future = executorService.submit(() -> {
            TableId tableId = TableId.of("dataset1", "table1");
            WriteChannelConfiguration writeChannelConfiguration = WriteChannelConfiguration.newBuilder(tableId)
                    .setWriteDisposition(JobInfo.WriteDisposition.WRITE_TRUNCATE)
                    .setFormatOptions(FormatOptions.parquet())
                    .build();
            JobId jobId = JobId.of("test-job-" + java.util.UUID.randomUUID());
            Thread.currentThread().interrupt();
            System.out.printf(" Thread Interrupted: %s\n",Thread.currentThread().isInterrupted());
            TableDataWriteChannel writer = bigQuery.writer(jobId, writeChannelConfiguration);
            System.out.printf(" Thread Interrupted: %s",Thread.currentThread().isInterrupted());
        });
        future.get();
    }


```
Log:

```
 Thread Interrupted: true
Exception in thread "main" java.util.concurrent.ExecutionException: com.google.cloud.bigquery.BigQueryException: java.lang.InterruptedException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at localtest.BQWriterIssueTest.main(BQWriterIssueTest.java:28)
Caused by: com.google.cloud.bigquery.BigQueryException: java.lang.InterruptedException
	at com.google.cloud.bigquery.BigQueryException.translateAndThrow(BigQueryException.java:122)
	at com.google.cloud.bigquery.TableDataWriteChannel.open(TableDataWriteChannel.java:97)
	at com.google.cloud.bigquery.TableDataWriteChannel.<init>(TableDataWriteChannel.java:41)
	at com.google.cloud.bigquery.BigQueryImpl.writer(BigQueryImpl.java:1436)
	at localtest.BQWriterIssueTest.lambda$main$0(BQWriterIssueTest.java:25)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.InterruptedException
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:543)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:66)
	at com.google.api.gax.retrying.BasicRetryingFuture.setAttemptFuture(BasicRetryingFuture.java:97)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:111)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.bigquery.TableDataWriteChannel.open(TableDataWriteChannel.java:81)
	... 8 more
```

I further checked the implementation and didn't find it clearing the interrupted flag.
Do you want to give it another try maybe after updating the dependency to `2.7.0`?

**Comment by stephaniewang526** [comment]
Closing due to inactivity. Please feel free to re-open if the issue persists.
