### ISSUE TITLE
BigQuery: after some amount of time/write jobs, all future write jobs fail with socket closed

### ISSUE THREAD

**Issue by akatkov7** [googleapis/java-bigquery#266]
#### Environment details

1. Specify the API at the beginning of the title.
2. OS type and version: Mac OSX 10.14.6
3. Java version: OpenJDK 1.8.0_232
4. bigquery version(s): 1.110.0

#### Steps to reproduce

  1. Run a program which uploads periodically over a period of time.
  2. Eventually, the upload fails with Socket closed for all uploads after that point.

#### Code example

```kotlin
private val bigQuery = BigQueryOptions.newBuilder()
        .setCredentials(
                GoogleCredentials.fromStream(credentialConfig)
        )
        .build()
        .service

private val tableId = TableId.of("...", "...")
private val writeConfig =
        WriteChannelConfiguration.newBuilder(tableId)
                .setFormatOptions(FormatOptions.csv())
                .setNullMarker("null")
                .build()

private val bqUploadingContext = newFixedThreadPoolContext(4, "bq-uploading")

// outputCSV is a file path
suspend fun uploadToBigQuery(outputCSV: String): Boolean {
    val writer = bigQuery.writer(writeConfig)
    // Write data to writer
    Channels.newOutputStream(writer).use {
        Files.copy(File(outputCSV), it)
    }
    writer.close()

    // Get load job
    val job = withContext(bqUploadingContext) { writer.job.waitFor() }
    // check the Job statistics, see if there were any errors, print how long the job took...
    return success
}
```

#### Stack trace
```
com.google.cloud.bigquery.BigQueryException: Socket closed
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:106)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.open(HttpBigQueryRpc.java:604)
	at com.google.cloud.bigquery.TableDataWriteChannel$2.call(TableDataWriteChannel.java:87)
	at com.google.cloud.bigquery.TableDataWriteChannel$2.call(TableDataWriteChannel.java:82)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.bigquery.TableDataWriteChannel.open(TableDataWriteChannel.java:81)
	at com.google.cloud.bigquery.TableDataWriteChannel.<init>(TableDataWriteChannel.java:41)
	at com.google.cloud.bigquery.BigQueryImpl.writer(BigQueryImpl.java:1249)
	at com.google.cloud.bigquery.BigQueryImpl.writer(BigQueryImpl.java:1240)
	at uploadToBigQuery // on the line: val writer = bigQuery.writer(writeConfig)
```

#### Any additional information below

I have a program which I'm running from IntelliJ which downloads some data, processes into a CSV, then uploads it to BigQuery. I have simplified the source code to the relevant stuff. `bigQuery` is initialized once at the start of the program and reused for the duration. Despite the context having 4 threads, these uploads are all happening in serial for now. The CSVs being uploaded are ~9MB and ~40k rows per upload.

The uploading code is mostly inspired by the Java example given here: https://cloud.google.com/bigquery/docs/loading-data-local#loading_data_from_a_local_data_source

However, if I run this program for a while, it will eventually crash with the Socket closed exception described above. If I catch the exception and try again, it will fail with the Socket closed exception again. I also tried recreating the `bigQuery` object by re-instantiating it, but it failed with something to the effect of "Failed to refresh access token: Socket closed".  On my latest run, it took ~5300 seconds and 231 uploads to happen. The uploads are roughly equally spread out across the run time. This happens consistently when I run my program for an extended period of time.

Thanks for any help. Let me know if there is an issue with my uploading process that could help fix this issue or if there is any other information needed.

Update:

Ran two more times on after updating to 1.110.1 and both ran for ~5000s and had 231 successful uploads as well before erroring as described above.

**Comment by pmakani** [comment]
@akatkov7 I tested it many times in java but not able to reproduce that error. could you please provide  the full sample code where you able to get that error ?

**Comment by pmakani** [comment]
@akatkov7 Closing this issue due to inactivity, feel free to reopen this issue if you are facing problem
